#!/bin/bash
# List all available container scripts and their purposes
# Usage: ./list-container-scripts.sh

echo "==================================="
echo "Container Development Scripts"
echo "==================================="
echo ""

echo "📦 DOCKER SCRIPTS"
echo "=================="
echo ""

echo "🔧 Installation & Setup:"
echo "  docker-install.yml                 - Install Docker on Ubuntu"
echo "  add-user-to-docker.yml             - Add user to Docker group"
echo "  yocto-in-docker-install.yml        - Complete Yocto Docker setup"
echo "  ros2-in-docker-install.yml         - Complete ROS2 Docker setup"
echo ""

echo "🚀 Container Management:"
echo "  start-yocto-container-docker.sh     - Create/manage Yocto Docker containers"
echo "  start-ros2-container.sh             - Create/manage ROS2 Docker containers"
echo "  restart-yocto-container.sh          - Restart Yocto Docker containers"
echo "  restart-ros2-container.sh           - Restart ROS2 Docker containers"
echo ""

echo "🔗 Connection Scripts:"
echo "  yocto-connect                       - Connect to Yocto Docker containers"
echo "  ros2-connect                        - Connect to ROS2 Docker containers"
echo "  docker-exec-it                      - Interactive Docker exec wrapper"
echo "  docker-exec-detached                - Detached Docker exec wrapper"
echo ""

echo "🎯 PODMAN SCRIPTS (Rootless Alternative)"
echo "========================================"
echo ""

echo "🔧 Installation & Setup:"
echo "  podman-install.yml                 - Install Podman (rootless by default)"
echo "  setup-podman-user.yml              - Configure Podman for current user"
echo "  yocto-in-podman-install.yml        - Complete Yocto Podman setup"
echo "  ros2-in-podman-install.yml         - Complete ROS2 Podman setup"
echo ""

echo "🚀 Container Management:"
echo "  start-yocto-container-podman.sh     - Create/manage Yocto Podman containers"
echo "  restart-yocto-container-podman.sh   - Restart Yocto Podman containers"
echo "  restart-ros2-container-podman.sh    - Restart ROS2 Podman containers"
echo ""

echo "🔗 Connection Scripts:"
echo "  yocto-podman-connect                - Connect to Yocto Podman containers"
echo "  ros2-podman-connect                 - Connect to ROS2 Podman containers"
echo "  podman-exec-it                      - Interactive Podman exec wrapper"
echo "  podman-exec-detached                - Detached Podman exec wrapper"
echo ""

echo "🛠️ SHARED UTILITIES"
echo "==================="
echo ""

echo "📚 Libraries & Common Functions:"
echo "  container-command-common.sh         - Shared functions for Docker & Podman"
echo "  run-container-common.sh             - Docker container runner library"
echo "  run-container-common-podman.sh      - Podman container runner library"
echo ""

echo "🔧 Prerequisites:"
echo "  install-ansible.sh                  - Install Ansible on Ubuntu/Debian"
echo ""

echo "⚙️ Command Installation:"
echo "  ensure-yocto-container-commands.sh  - Install commands in Docker containers"
echo "  ensure-yocto-container-commands-podman.sh - Install commands in Podman containers"
echo "  add-commands-to-container.sh        - Generic command installer"
echo ""

echo "🔍 Diagnostics & Utilities:"
echo "  container-diagnostic.sh             - Container diagnostics and troubleshooting"
echo "  container-shell-setup.sh            - Container shell environment setup"
echo "  container-utils.sh                  - Container utility functions"
echo "  container-watch.sh                  - Container lifecycle monitoring"
echo "  verify-container.sh                 - Verify container setup"
echo ""

echo "🧹 Maintenance:"
echo "  cleanup-container-images.sh         - Clean up unused container images"
echo ""

echo "📖 DOCUMENTATION"
echo "================="
echo ""
echo "  README.md                           - Main documentation"
echo "  CONTAINER_COMMANDS.md               - Container commands guide"
echo "  CONTAINER_INSTALLATION.md          - Installation procedures"
echo "  POKY_CONTAINER_COMMANDS.md          - Yocto/CROPS specific commands"
echo "  VSCODE_CONTAINER_ACCESS.md          - VS Code integration guide"
echo "  PODMAN_SCRIPTS.md                   - Podman scripts documentation"
echo ""

echo "🎮 QUICK START EXAMPLES"
echo "======================="
echo ""

echo "🐳 Docker Workflow:"
echo "  1. ansible-playbook docker-install.yml"
echo "  2. ansible-playbook yocto-in-docker-install.yml"
echo "  3. ./yocto-connect"
echo ""

echo "📦 Podman Workflow (Rootless):"
echo "  1. ansible-playbook podman-install.yml"
echo "  2. ansible-playbook yocto-in-podman-install.yml"
echo "  3. ./yocto-podman-connect yocto-workspace-container"
echo ""

echo "🔧 Manual Container Management:"
echo "  ./start-yocto-container-docker.sh --name my-yocto"
echo "  ./start-yocto-container-podman.sh --name my-yocto"
echo ""

echo "💡 CONTAINER COMMANDS (Available in all containers)"
echo "=================================================="
echo ""
echo "  container-help                      - Show container help"
echo "  container-detach                    - Detach (keep running)"
echo "  container-stop                      - Stop container"
echo "  container-remove                    - Remove container"
echo ""

echo "✨ KEY DIFFERENCES"
echo "=================="
echo ""
echo "🐳 Docker:"
echo "  - Requires root/docker group"
echo "  - Uses systemd daemon"
echo "  - System-wide installation"
echo ""
echo "📦 Podman:"
echo "  - Completely rootless"
echo "  - No daemon required"
echo "  - User-specific containers"
echo "  - Better security isolation"
echo ""

echo "For detailed usage, see README.md and CONTAINER_COMMANDS.md"
